# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml 

trigger:
- none

pool:
  vmImage: 'Ubuntu-latest'

variables:
  buildplatform: 'Any CPU'
  buildConfiguration: "Release"
  solution: '**/PTPL.FitOS.ColoursAPI.sln'
  project: '**/PTPL.FitOS.ColoursAPI/PTPL.FitOS.ColoursAPI.csproj'

steps:
  - task: NuGetToolInstaller@1
    name: 'NuGetToolInstaller'
    displayName: 'NuGet Tool Installer'

  - task: NuGetCommand@2
    name: 'NuGetRestore'
    displayName: 'NuGet restore packages'  
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    name: 'Test'
    displayName: 'Run test'  
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'
      
  

  - task: DotNetCoreCLI@2
    name: 'Publish'
    displayName: 'Publish'  
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(project)'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.AtrifactStagingDirectory)'
      zipAfterPublish: false
      
  - task: PublishBuildArtifacts@1
    name: 'PublishBuildArtifacts'
    displayName: 'Publish Build Artifacts'    
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'ColourAPI_ServiceProject'
      publishLocation: 'Container'
  
